### ISSUE TITLE
empty frame grabbed when calibration time is longer than the actual video

### ISSUE THREAD

**Issue by phildong** [ZachPenn/BehaviorTracking#1]
In `FreezeAnalysis_Calibration.ipynb`, when `cal_sec` is set to be longer than the video, presumably when `cal_sec * fps` is larger than the total frame count of the video, empty frames will be grabbed during calibration and following `cv2.cvtColor` would fail:

```python
%%output size=100
hist = fz.Calibrate(fpath,cal_sec,cal_pix,fps,SIGMA)
hist
```

    ---------------------------------------------------------------------------

    error                                     Traceback (most recent call last)

    <ipython-input-10-aecaa9fcbc1d> in <module>
    ----> 1 hist = fz.Calibrate(fpath,cal_sec,cal_pix,fps,SIGMA)
          2 hist

    ~/Documents/git/BehaviorTracking/BehaviorTracking_Functions.py in Calibrate(fpath, cal_sec, cal_pix, fps, SIGMA)
        460 
        461         #Process frame
    --> 462         frame_new = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        463         frame_new = mh.gaussian_filter(frame_new,sigma=SIGMA) # used to reduce influence of jitter from one frame to the next
        464 

    error: OpenCV(3.4.4) ../modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

It would be nice to throw a more informative exception earlier.

**Comment by ZachPenn** [comment]
Thanks for catching this.  This issue has now been resolved.  If fewer frames are present than cal_sec, calibration will terminate early without an error.
